name: CI
on:
  push:
    branches:
      - '*'

jobs:

  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
    - name: Build mediafx image
      uses: docker/build-push-action@v5
      with:
        context: builders/linux
        tags: mediafx
        load: true
        target: mediafx
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build mediafx-vulkan image
      uses: docker/build-push-action@v5
      with:
        context: builders/linux
        tags: mediafx-vulkan
        load: true
        target: mediafx-vulkan  
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Install mediaFX
      run: DOCKER_OPTS="-e MEDIAFX_TEST=1" builders/linux/docker-run.sh /mediafx/builders/linux/mediafx-build.sh
    - name: Install mediaFX vulkan
      run: DOCKER_OPTS="-e MEDIAFX_TEST=1" TARGET=mediafx-vulkan builders/linux/docker-run.sh /mediafx/builders/linux/mediafx-build.sh
    - name: iwyu
      run: builders/linux/docker-run.sh /mediafx/builders/linux/iwyu.sh

  macos:
    runs-on: macos-13
    env:
      XCODE_VER: "15.0"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Xcode
      run: |
        sudo xcode-select -s "/Applications/Xcode_${XCODE_VER}.app"
    - name: Restore cached installation
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: build/macos/installed
        key: ${{ runner.os }}-${{ hashFiles('builders/macos/versions') }}-${{ env.XCODE_VER }}
    - name: Build installation
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: |
        builders/macos/install-qt6.sh
    - name: Save cached installation
      uses: actions/cache/save@v3
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        path: build/macos/installed
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
    - name: Install mediaFX
      run: |
        MEDIAFX_TEST=1 builders/macos/mediafx-build.sh
